### ISSUE TITLE
SMLets support for SM2016

### ISSUE THREAD

**Issue by antonGritsenko** [SMLets/SMLets#1]
SMLets are not properly working on SM2016, also .NET Framework support will be nice to have.

**Comment by rdbartram** [comment]
which version of .NET are you migrating to and why? also, do we have a list of things that aren't working in 2016 so we can start addressing them?

**Comment by antonGritsenko** [comment]
.NET 4.5.1, because SCSM 2016 use this version. There are no any new features in SCSM 2016.
So the only change that needs to be done is configuration of the compiler, nothing else.

**Comment by rdbartram** [comment]
My latest builds are compiled in 4.5.1. I'll make a pull request as soon as I migrate all the code out of the build.ps1 script. FYI I was using smlets on scsm 2016 when compiled on .NET 3.5

**Comment by n-pedersen** [comment]
Any news here?
I'm testing the SMLets 0.5 for SCSM 2016 (Upgraded) on Windows Server 2012 R2 and it seems to work.
However, orchestrator is another story. I'm testing on orchestrator 2016, on Windows Server 2016, it works, but only in an x64 Powershell v5 session, not in the 'native' orchestrator session, which is Powershell v2 and x86. Seems like a minor issue, but a full support for SCSM 2016 would be great.

**Comment by antonGritsenko** [comment]
Will be available with v.0.7
