### ISSUE TITLE
Incorrect "Required version"

### ISSUE THREAD

**Issue by shoootyou** [SMLets/SMLets#12]
Hello,

On PowerShell Galley only has version 0.5.0.1 not the version 0.7.2012.0

Please, fix this.

Thanks a lot!

**Comment by hjorslev** [comment]
Nor is 0.7.2016.0 to be found in the [PowerShell Gallery](https://www.powershellgallery.com/packages?q=SMLets).

**Comment by antonGritsenko** [comment]
Later better than never :) New version published for both, SM 2012 and SM2016+.
