### ISSUE TITLE
PowerShell 7

### ISSUE THREAD

**Issue by hjorslev** [SMLets/SMLets#13]
I am not well versed in the different frameworks, but as far as I can see this module uses 3.5 for SCSM 2012 and 4.5.1 for SCSM 2016. PowerShell 7 uses 3.1. .NET Core.

What exactly does it take to make this module supported in PS7

**Comment by AdhocAdam** [comment]
I personally tend to think this requires an update from the System Center teams _first_ as you can't even run the native Operations Manager or Service Manager cmdlets in 7 without errors.

The only workaround I'm aware of is the implicit remoting introduced with the upgraded version of Import-Module which you might already know is really just v5.1 in a v7 wrapper.

**Comment by antonGritsenko** [comment]
Why do you need the psh 7 support? Entire SC stack targeted to full net framework, so bringing support just for cmdlets will be really hard

**Comment by hjorslev** [comment]
Thanks for your answers, much appreciated!

I primarily use SMLets to add analyst comments / creating new IR / easily retrieving a user's newest work items, so I don't have a major need. I was merely curious as there are features in PS 7 that I'd like to use in my daily work and wondered which way I should proceed in using SMLets in PS 7.

I think I will experiment some more with Import-Module -UseWindowsPowerShell.

**Comment by AdhocAdam** [comment]
As an example @hjorslev -

```powershell
Import-Module smlets -UseWindowsPowerShell
$pwshSession = Get-PSSession -Name "WinPSCompatSession"
Invoke-Command -Session $pwshSession -Command {$irClass = Get-SCSMClass -name "System.WorkItem.Incident$"; Get-SCSMObject -class $irClass -filter "Name -eq 'IR1234'"}
```

**Comment by hjorslev** [comment]
Thanks Adam! It works. Is there a way to return the $User variable without it being deserialized so I can keep all the methods etc? I have attempted this:
```powershell
if ($PSVersionTable.PSVersion.Major -eq 7) {
	Write-Verbose -Message 'Using SMLets through WinPSCompatSession for PS 7 compatibility.'
	$WinPSCompatSession = Get-PSSession -Name WinPSCompatSession
	$User = Invoke-Command -Session $WinPSCompatSession -ScriptBlock {
		# Get work items (ie. Incidents, SRQs, Activities, etc) affecting user.
		Get-SCSMObject -Class (Get-SCSMClass -Name ^Microsoft.AD.User$ -ComputerName $using:SCSMServer) -Filter "UserName -eq '$using:UserName'" -ComputerName $using:SCSMServer
		return $User
	}
	$AffectedRelationship = Invoke-Command -Session $WinPSCompatSession -ScriptBlock {
		# Class for affected user relationship.
		Get-SCSMRelationshipClass -Name System.WorkItemAffectedUser$ -ComputerName $using:SCSMServer

		return $AffectedRelationship
	}
	$Incidents = Invoke-Command -Session $WinPSCompatSession -ScriptBlock {
		$Incidents = (Get-SCSMRelationshipObject -Relationship $AffectedRelationship -ByTarget $User -ComputerName $using:SCSMServer).Where{ $_.SourceObject.DisplayName.Substring(0, 3) -notlike "MA*" } | Sort-Object -Property LastModified -Descending

		return $Incidents
	}
}
```

When it return $Incidents.SourceObject in PS 7 the properties of ClassName, DisplayName and LastModified are gone.

I can make the above work, but I am a little curious as to if there is an easier way. I have learned that I can use $using:UserName to pass a local variable into the remote session. Can I do it as easily with your example in mind and get `$irClass` from the remote session to the local session?
```powershell
Invoke-Command -Session $pwshSession -Command {$irClass = Get-SCSMClass -name "System.WorkItem.Incident$"; Get-SCSMObject -class $irClass -filter "Name -eq 'IR1234'"}
```

**Comment by AdhocAdam** [comment]
🤔

**Comment by hjorslev** [comment]
Just a follow up:

I were suggested to try converting the objects to JSON and that actually worked if you look at the example below:
```powershell
if ($PSVersionTable.PSVersion.Major -eq 7) {
    Write-Verbose -Message 'Using SMLets through WinPSCompatSession for PS 7 compatibility.'
    $WinPSCompatSession = Get-PSSession -Name WinPSCompatSession
    $User = Invoke-Command -Session $WinPSCompatSession -ScriptBlock {
        # Get work items (ie. Incidents, SRQs, Activities, etc) affecting user.
        $User = Get-SCSMObject -Class (Get-SCSMClass -Name ^Microsoft.AD.User$ -ComputerName $using:SCSMServer) -Filter "UserName -eq '$using:UserName'" -ComputerName $using:SCSMServer
        return $User
    }
    $AffectedRelationship = Invoke-Command -Session $WinPSCompatSession -ScriptBlock {
        # Class for affected user relationship.
        $AffectedRelationship = Get-SCSMRelationshipClass -Name System.WorkItemAffectedUser$ -ComputerName $using:SCSMServer

        return $AffectedRelationship
    }
    $Incidents = Invoke-Command -Session $WinPSCompatSession -ScriptBlock {
        $Incidents = (Get-SCSMRelationshipObject -Relationship $AffectedRelationship -ByTarget $User -ComputerName $using:SCSMServer).Where{ $_.SourceObject.DisplayName.Substring(0, 3) -notlike "MA*" } | Sort-Object -Property LastModified -Descending | ConvertTo-Json

        return $Incidents
    }

    $Incidents = $Incidents | ConvertFrom-JSON
}
```
This led me keep the nested objects of $Incidents.SourceObject 😃
