### ISSUE TITLE
Does SCSM Cmdlets support SCSM 2019 ?

### ISSUE THREAD

**Issue by wyatt-wong** [SMLets/SMLets#16]
May I know the current SCSM Cmdlets support SCSM 2019 or not ?

**Comment by pwahlmueller** [comment]
Yes, it works.

**Comment by antonGritsenko** [comment]
@wyatt-wong I'm really sorry for missing your question. @pwahlmueller is absolutely correct, version for SM2016 will work (and supported) with SM2019. Nothing need to be changed.
