### ISSUE TITLE
Get-SCSMUserRole output isn't very readable

### ISSUE THREAD

**Issue by rdbartram** [SMLets/SMLets#3]
The standard Get-SCSMUserRole command from ServerManager Console return type Microsoft.EnterpriseManagement.ServiceManager.Sdk.UserRoles.Role.

This is much nicer than the current return type Microsoft.EnterpriseManagement.Security.UserRole.

Would it be possible to create a new class inherited from Microsoft.EnterpriseManagement.Security.UserRole and add additional properties from Microsoft.EnterpriseManagement.ServiceManager.Sdk.UserRoles.Role

**Comment by antonGritsenko** [comment]
We can't use Microsoft.EnterpriseManagement.ServiceManager.Sdk.UserRoles.Role directly because it's not a part of the SDK (defined in Microsoft.EnterpriseManagement.ServiceManager.Sdk.dll).

**Comment by antonGritsenko** [comment]
Implemented in 0.7
